function thr = MLO_10118829_III(randnum, simTime, radiusList, isSTR, bandAndChannel,channelBW, mcs)
 
%kod do odtworzenia wykresu 6 z badania 10118829, 


    % Set seed of random number generator for reproducible results
    rng(randnum,"combRecursive");
    % Set simulation time
    simulationTime = simTime;

    phyAbstraction="tgax-evaluation-methodology";
    macAbstraction = true;
    
    % Create wireless network simulator
    networkSimulator = wirelessNetworkSimulator.init;
    % calculate number of links
    numLinks = size(bandAndChannel,1);
    
    aggregationLimit = 1024;
    transmissionPower = 20;
    
   
    if isSTR
        
        for linkIdx = 1:numLinks
            apLinkCfg(linkIdx) = wlanLinkConfig( ...
                BandAndChannel=bandAndChannel(linkIdx,:), ...
                ChannelBandwidth=channelBW, ...
                MCS=mcs, ...
                NumSpaceTimeStreams=2, ...
                NumTransmitAntennas=2,...
                MPDUAggregationLimit=aggregationLimit, ...
                TransmitPower=transmissionPower);
            staSTRLinkCfg(linkIdx) = wlanLinkConfig( ...
                BandAndChannel=bandAndChannel(linkIdx,:), ...
                ChannelBandwidth=channelBW,...
                MCS=mcs, ...
                NumSpaceTimeStreams=2, ...
                NumTransmitAntennas=2, ...
                MPDUAggregationLimit=aggregationLimit, ...
                TransmitPower=transmissionPower);
        end
        
        apMLDCfg = wlanMultilinkDeviceConfig(Mode="AP",LinkConfig=apLinkCfg);
        staSTRMLDCfg = wlanMultilinkDeviceConfig(Mode="STA",LinkConfig=staSTRLinkCfg);
         
        [staPosition, apPosition] = randomPositionsFermat(1, radiusList(1));
        apNode = wlanNode(Position=apPosition,Name="AP",DeviceConfig=apMLDCfg, PHYAbstractionMethod=phyAbstraction,MACFrameAbstraction=macAbstraction);
        staNode = wlanNode( ...
            Position=staPosition, ...
            Name="STR STA ", ...
            DeviceConfig=staSTRMLDCfg, ...
            PHYAbstractionMethod=phyAbstraction, ...
            MACFrameAbstraction=macAbstraction);
        
        
        associateStations(apNode,staNode, FullBufferTraffic="DL");
           
    else
        
        apLinkCfg = wlanLinkConfig( ...
            BandAndChannel=bandAndChannel, ...
            ChannelBandwidth=channelBW,...
            MCS=mcs, ...
            NumSpaceTimeStreams=2, ...
            NumTransmitAntennas=2, ...
            MPDUAggregationLimit=aggregationLimit,...
            TransmitPower=transmissionPower);
        staEMLSRLinkCfg = wlanLinkConfig( ...
            BandAndChannel=bandAndChannel, ...
            ChannelBandwidth=channelBW, ...
            NumTransmitAntennas=1, ...
            NumSpaceTimeStreams=1, ...
            MCS=mcs, ...
            MPDUAggregationLimit=aggregationLimit,...
            TransmitPower=transmissionPower);
        
        apMLDCfg = wlanMultilinkDeviceConfig(Mode="AP",LinkConfig=apLinkCfg);
        staEMLSRMLDCfg = wlanMultilinkDeviceConfig(Mode="STA",LinkConfig=staEMLSRLinkCfg,EnhancedMultilinkMode="EMLSR");

        [staPosition, apPosition] = randomPositionsFermat(1, radiusList(1));
        apNode = wlanNode(Position=apPosition,Name="AP",DeviceConfig=apMLDCfg, PHYAbstractionMethod=phyAbstraction,MACFrameAbstraction=macAbstraction);
        staNode = wlanNode( ...
            Position=staPosition, ...
            Name="EMLSR STA " , ...
            DeviceConfig=staEMLSRMLDCfg, ...
            PHYAbstractionMethod=phyAbstraction, ...
            MACFrameAbstraction=macAbstraction);
      
         
         associateStations(apNode,staNode, FullBufferTraffic="DL");
        
    end

    
    for linkIdx = 1:numLinks
            
        apCfg(linkIdx) = wlanDeviceConfig(Mode="AP", MCS=mcs, ChannelBandwidth=channelBW, BandAndChannel=bandAndChannel(linkIdx, :));
        staCfg(linkIdx) = wlanDeviceConfig(Mode="STA", MCS=mcs, ChannelBandwidth=channelBW,BandAndChannel=bandAndChannel(linkIdx, :));
        [staPositionSingle, apPositionSingle] = randomPositionsFermat(1, radiusList(linkIdx+1));
        apNodesSingle(linkIdx) = wlanNode(...
            Position=apPositionSingle,...
            Name="AP",...
            DeviceConfig=apCfg(linkIdx),...
            PHYAbstractionMethod=phyAbstraction,...
            MACFrameAbstraction=macAbstraction);
        staNodesSingle(linkIdx) = wlanNode( ...
            Position=staPositionSingle, ...
            Name="SL STA " + linkIdx, ...
            DeviceConfig=staCfg(linkIdx), ...
            PHYAbstractionMethod=phyAbstraction, ...
            MACFrameAbstraction=macAbstraction);
        
        
        associateStations(apNodesSingle(linkIdx),staNodesSingle(linkIdx), FullBufferTraffic="DL");

    end

    apNodes = [apNode apNodesSingle];
    staNodes = [staNode staNodesSingle];
    nodes = [apNodes staNodes];

    % Add channel model to the simulator
    channel = hSLSTGaxMultiFrequencySystemChannel(nodes);
    addChannelModel(networkSimulator,channel.ChannelFcn);

    % Add nodes to network simulator
    addNodes(networkSimulator,nodes);

    % Create node performance visualization object
    perfViewerObj = hPerformanceViewer(nodes,simulationTime);

    % Run the simulation
    run(networkSimulator,simulationTime);
   
    % Calculate throughput at AP
    apThroughput = throughput(perfViewerObj,[apNodes(:).ID]);
    thr = apThroughput;

end